In [1]:
import numpy as np

In [2]:
# TODO: Code can be significantly optimized if this direction proves promising.
# This is because the matrix is block diagonal with the hamming distances
# forming the entries along the diagonal. Can be quickly generated using two
# nested for loops.

In [3]:
def generateBitstrings(n):
    bitstrings = []
    for i in range(2**n):
        bitstrings.append(f'{i:0{n}b}')
    return bitstrings

# print(generateBitstrings(3))

In [4]:
def addBitstrings(x, y):
    z = []
    for i, bit in enumerate(x):
        z.append(str((int(bit) + int(y[i])) % 2))
    return ''.join(z)

# print(addBitstrings('0011', '0101'))

In [5]:
# def invertBitstring(x):
#     y = []
#     for bit in x:
#         y.append('1' if bit == '0' else '0')
#     return ''.join(y)

# print(invertBitstring('0011'))

In [6]:
def generateF(bitstrings, s):
    f = {}
    for x in bitstrings:
        if x not in f:
            y = x if x[-1] == '0' else addBitstrings(x, s)
            f[y] = y
            f[addBitstrings(y, s)] = y
    return f

# print(generateF(generateBitstrings(3), '111'))

In [7]:
def hammingDistance(x, y):
    dist = 0
    for i, bit in enumerate(x):
        if bit != y[i]:
            dist += 1
    return dist

# print(hammingDistance('0011', '0101'))

In [8]:
def bitstringToVector(x):
    v = np.zeros(2**len(x))
    v[int(x, 2)] = 1
    return v

# print(bitstringToVector('101'))

In [9]:
def hamiltonian(bitstrings, f):
    n = len(bitstrings[0])
    outerSum = np.zeros((2**(2*n), 2**(2*n)))
    for x in bitstrings:
        v = bitstringToVector(x)
        innerSum = np.zeros((2**n, 2**n))
        for y in bitstrings:
            w = bitstringToVector(y)
            innerSum += hammingDistance(y, f[x]) * np.outer(w, w)
        outerSum += np.kron(np.outer(v, v), innerSum)
    return outerSum

# bitstrings = generateBitstrings(2)
# print(bitstrings)
# f = generateF(bitstrings, bitstrings[-1])
# print(f)
# hamiltonian(bitstrings, f)

In [10]:
for n in range(2, 6):
    bitstrings = generateBitstrings(n)
    f = generateF(bitstrings, bitstrings[-1])
    print(hamiltonian(bitstrings, f))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 3.]]
[[0. 0. 0. ... 0. 0. 0.]
 [

In [20]:
def solveQubo(q, n):
    mins = []
    for i in range(2**(2*n)):
        v = np.zeros(2**(2*n), dtype=int)
        v[i] = 1
        x = ''.join(list(map(str, v.tolist())))
        print(x, v.T @ q @ v)
        if v.T @ q @ v == 0:
            mins.append(x)
    return mins

# n = 3
# bitstrings = generateBitstrings(n)
# f = generateF(bitstrings, bitstrings[-1])
# q = hamiltonian(bitstrings, f)
# results = solveQubo(q, n)
# print(results)

# TODO: Verify that q^2 gives the same results

In [23]:
def interpretResults(results, n):
    decodedResults = set()
    for result in results:
        index = result.find('1')
        # index = result[::-1].find('1')
        print(f'{index:0{2*n}b}')
        decodedResults.add(f'{index:0{2*n}b}'[n:])
    return decodedResults

# interpretResults(results, n) #Bug here...should be 11 and 00

In [24]:
n = 2
bitstrings = generateBitstrings(n)
f = generateF(bitstrings, bitstrings[-1])
q = hamiltonian(bitstrings, f)
results = solveQubo(q, n)
interpretResults(results, n)

1000000000000000 0.0
0100000000000000 1.0
0010000000000000 1.0
0001000000000000 2.0
0000100000000000 1.0
0000010000000000 2.0
0000001000000000 0.0
0000000100000000 1.0
0000000010000000 1.0
0000000001000000 2.0
0000000000100000 0.0
0000000000010000 1.0
0000000000001000 0.0
0000000000000100 1.0
0000000000000010 1.0
0000000000000001 2.0
0000
0110
1010
1100


{'00', '10'}

In [14]:
# Interpreting this matrix directly as a QUBO does not appear to be working...